server:
  port: 2333

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: false   # keep builtin YT disabled

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    # Try a robust client mix. The order is a preference hint:
    clients:
      - WEB
      - MUSIC
      - ANDROID
      - TVHTML5EMBEDDED
      - WEBEMBEDDED
    remoteCipher:
      url: "http://localhost:8001"


  # If you haven't actually added the lavasrc jar, disable it to reduce noise:
  lavasrc:
    enabled: false
